=== mcenirm-forks/nasa-dryden-dt/XML_startup_P3_example/inds_startup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="startup" type="StartupType"/>

<xsd:complexType name="StartupType">
	<xsd:sequence>
		<xsd:element ref="command" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="PortType" >
	<xsd:attribute name="type" type="xsd:string" use="required" />
	<xsd:attribute name="port" type="xsd:string" />
	<!-- type="rbnb" specific attributes, grouped here for simplicity. -->
	<xsd:attribute name="name" type="xsd:string" /> <!-- of Source or Sink -->
	<xsd:attribute name="channel" type="xsd:string" />
	<xsd:attribute name="cacheFrames" type="xsd:nonNegativeInteger"/>
	<xsd:attribute name="archiveFrames" type="xsd:nonNegativeInteger"/>
	<xsd:attribute name="overwriteArchive" type="xsd:boolean" />
</xsd:complexType>

<xsd:complexType name="CommandType" abstract="true">
	<xsd:sequence>
		<xsd:element name="input" type="PortType" 
				minOccurs="0" maxOccurs="unbounded"/>
		<xsd:element name="output" type="PortType" 
				minOccurs="0" maxOccurs="unbounded" />
	</xsd:sequence>
	<xsd:attribute name="initialDirectory" type="xsd:string"/>
	<xsd:attribute name="logFile" type="xsd:string"/>
	<xsd:attribute name="tag" type="xsd:string"/>	
</xsd:complexType>

<xsd:complexType name="JavaCommandType" abstract="true">
	<xsd:complexContent>
		<xsd:extension base="CommandType">
			<xsd:attribute name="jvmMaxHeap" type="xsd:string"/>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="PluginType" abstract="true">
	<xsd:complexContent>
		<xsd:extension base="JavaCommandType">
			<xsd:sequence>
				<xsd:element name="plugin" type="PortType" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:element name="command" type="CommandType" 
		abstract="true" block="restriction" />

<!-- Non-java commands: -->
<xsd:element name="del" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="CommandType">
				<xsd:attribute name="file" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="sleep" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="CommandType">
				<xsd:attribute name="duration_ms" type="xsd:nonNegativeInteger"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<!-- Java applications: -->
<xsd:element name="dataTurbine" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="name" type="xsd:string"/>
				<xsd:attribute name="address" type="xsd:string"/>
				<xsd:attribute name="parent" type="xsd:string"/>
				<xsd:attribute name="loadArchivesAtStart" type="xsd:boolean"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="xmlDemux" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="chanNameFromID" type="xsd:boolean"/>
				<xsd:attribute name="silentMode" type="xsd:boolean"/>
				<xsd:attribute name="xmlFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="csvDemux" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="chanNameFromID" type="xsd:boolean"/>
				<xsd:attribute name="checkEmbeddedTimestamp" type="xsd:boolean"/>
				<xsd:attribute name="dateFormat" type="xsd:string"/>
				<xsd:attribute name="silentMode" type="xsd:boolean"/>
				<xsd:attribute name="xmlFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="udpCapture" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="httpMonitor" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="configFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="tomcat" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="CommandType"/>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="timeDrive" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="multiUserMode">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="off"/>
							<xsd:enumeration value="ip"/>
							<xsd:enumeration value="username_password"/>
							<xsd:enumeration value="combination"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>


<!-- DataTurbine Plugins -->
<xsd:element name="png" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="width" type="xsd:integer"/>
				<xsd:attribute name="height" type="xsd:integer"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="toString" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType"/>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="thumbNail" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="scale" type="xsd:double"/>
				<xsd:attribute name="quality" type="xsd:double"/>
				<xsd:attribute name="maxImages" type="xsd:positiveInteger"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="trackData" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="noGUI" type="xsd:boolean"/>
				<xsd:attribute name="configFile" type="xsd:string"/>
				<xsd:attribute name="compression" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="trackKML" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="consolidateResponse" type="xsd:boolean"/>
				<xsd:attribute name="noGUI" type="xsd:boolean"/>
				<xsd:attribute name="configFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="deadReckoning" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="maxLatency_sec">
					<xsd:simpleType>
						<xsd:restriction base="xsd:double">
							<xsd:minInclusive value="0"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

</xsd:schema>

=== mcenirm-forks/nasa-dryden-dt/XML_startup_P3_example/P3_startup.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- A first cut at describing the P3 INDS system using Bill Finger's INDS Execution Manager schema.                 -->
<!-- Only the RBNB Server is started in a separate directory; all other processes are started in the base directory. -->

<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd" >
	
	<!-- Tomcat -->
	<tomcat />
	
	<!-- Server -->
	<!-- Questions:
		1. will the execution manager use $RBNBBIN to know which version of RBNB to launch?
		2. need to add ability to send flags to Java, for example "-mx1024M" -->
	<del initialDirectory="Server" file="rbnb.log" />
	<dataTurbine initialDirectory="Server" logFile="rbnb.log" name="INDS" address=":3333" />
	<sleep duration_ms="15000" />
	
	<!-- Delete all the log files -->
	<del file="*.log" />
	
	<!-- Jobs/KMLTrack -->
	<trackKML logFile="TrackKMLDC8.log" name="TrackKML_DC8" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigDC8.txt" />
	<trackKML logFile="TrackKMLP3B.log" name="TrackKML_P3B" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigP3B.txt" />
	<trackKML logFile="TrackKMLB200.log" name="TrackKML_B200" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigB200.txt" />
	<trackKML logFile="TrackKMLNOAAP3.log" name="TrackKML_NOAAP3" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigNOAAP3.txt" />
	<trackKML logFile="TrackKMLCV580.log" name="TrackKML_CV580" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigCV580.txt" />
	<trackKML logFile="TrackKMLTwinOtter.log" name="TrackKML_TwinOtter" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigTwinOtter.txt" />
	<trackData logFile="TrackDataDC8.log" name="TrackData_DC8" noGUI="true" configFile="TrackDataConfigDC8.txt" />
	<trackData logFile="TrackDataP3B.log" name="TrackData_P3B" noGUI="true" configFile="TrackDataConfigP3B.txt" />
	<trackData logFile="TrackDataB200.log" name="TrackData_B200" noGUI="true" configFile="TrackDataConfigB200.txt" />
	<trackData logFile="TrackDataNOAAP3.log" name="TrackData_NOAAP3" noGUI="true" configFile="TrackDataConfigNOAAP3.txt" />
	<trackData logFile="TrackDataCV580.log" name="TrackData_CV580" noGUI="true" configFile="TrackDataConfigCV580.txt" />
	<trackData logFile="TrackDataTwinOtter.log" name="TrackData_TwinOtter" noGUI="true" configFile="TrackDataConfigTwinOtter.txt" />
	<sleep duration_ms="2000" />
	
	<!-- Jobs/TimeDrive -->
	<timeDrive logFile="timedrive.log" listenPort="4000" webserverAddress="localhost" multiUserMode="2" />
	<sleep duration_ms="2000" />
	
	<!-- Jobs/PlugIns -->
	<png name="PNGPlugIn" hostAddress="localhost:3333" width="320" height="200"  />
	<sleep duration_ms="1000" />
	<toString name="ToString" />
	<sleep duration_ms="1000" />
	<thumbNail name="ThumbNail" scale="0.5" quality="0.9" maxImages="10" />
	<sleep duration_ms="5000" />
	
	<!-- DC8 project -->
	<xmlDemux -a localhost:3333 -A localhost:3333 -S -I -i DC8-5000-cap/UDP -x IWG1_GTR_OUT.XML -c200 -K1000000 >& IWG1Demux.log  &
	<sleep duration_ms="1000" />
	
	<!-- P3B project -->
	XMLDemux -a localhost:3333 -A localhost:3333 -S -I -i P3B-5700-cap/UDP -x IWG1_INDS_OUT.XML -c200 -K1000000 >& IWG1Demux.log &
	<sleep duration_ms="1000" />
	XMLDemux -a localhost:3333 -A localhost:3333 -S -I -i P3B-5750-cap/UDP -x SCAN_GTR_OUT.XML -c200 -K1000000 >& HskpngDemux.log &
	<sleep duration_ms="2000" />
	
	<!-- B200 project -->
	CSVDemux -a localhost:3333 -A localhost:3333 -d yyyyMMdd\'T\'HHmmss -i B200/B200_ASR_reduced.txt -x B200.xml -c200 -K1000000 -p -S >& CSVDemux.log  &
	<sleep duration_ms="1000" />
	
	<!-- NOAA P3 project -->
	CSVDemux -a localhost:3333 -A localhost:3333 -d yyyyMMdd\'T\'HHmmss -i NOAA_P3/WP3D.txt -x NOAA_P3.xml -c200 -K1000000 -p -S >& CSVDemux.log  &
	<sleep duration_ms="1000" />
	
	<!-- CV580 project -->
	CSVDemux -a localhost:3333 -A localhost:3333 -d yyyyMMdd\'T\'HHmmss -i CV580/_CSV -x CV580.xml -c200 -K1000000 -p -S -o CV580_IWG1 >& CSVDemux.log &
	<sleep duration_ms="1000" />
	
	<!-- Twin Otter project -->
	CSVDemux -a localhost:3333 -A localhost:3333 -d yyyy-MM-dd\'T\'HH:mm:ss\'Z\' -i P3B-5800-cap/UDP -x TwinOtter.xml -c200 -K1000000 -p -S >& TwinOtterDemux.log  &
	DeadReckoningPlugIn -m 1800 >& DeadReckoning.log &
	<sleep duration_ms="1000" />
	
	<sleep duration_ms="5000" />
	
</startup>

=== mcenirm-forks/nasa-dryden-dt/G-III/G-III_startup.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Gumstix Beacon project -->

<!--startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd"-->
<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/user/DryScan/nasa-dryden-dt/UWyoKingAir/inds_startup.xsd">
	
	<!-- Tomcat -->
	<!-- Doesn't work with the new Tomcat (apache-tomcat-6.0.18) -->
	<!-- tomcat initialDirectory="Tomcat" logFile="tommy.log">
		<input type="tcp" port="localhost:80" />
	</tomcat>
	<sleep duration_ms="5000"/-->
	
	<!-- Server -->
	<del initialDirectory="Server" file="rbnb.log"/>
	<dataTurbine jvmMaxHeap="1024M" initialDirectory="Server" logFile="rbnb.log" name="INDS" address=":3333" tag="BeaconDT"/>
	<sleep duration_ms="15000"/>
	
	<!-- Jobs/KMLTrack -->
	<del initialDirectory="Jobs/KMLTrack" file="*.log"/>
	<trackKML initialDirectory="Jobs/KMLTrack" logFile="TrackKML.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfig.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML" />
	</trackKML>
	<trackData initialDirectory="Jobs/KMLTrack" logFile="TrackData.log" noGUI="true" configFile="TrackDataConfig.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData" />
	</trackData>
	
	<!-- Jobs/TimeDrive -->
	<del initialDirectory="Jobs/TimeDrive" file="*.log"/>
	<timeDrive initialDirectory="Jobs/TimeDrive" logFile="timedrive.log" multiUserMode="ip">
	    <input type="tcp" port="4000"/>
	    <output type="tcp" port="localhost:80"/>
	</timeDrive>
	
	<!-- Jobs/PlugIns -->
	<del initialDirectory="Jobs/PlugIns" file="*.log"/>
	<png initialDirectory="Jobs/PlugIns" logFile="png.log" width="320" height="200">
	    <plugin type="rbnb" port="localhost:3333" name="PNGPlugIn" />
	</png>
	<toString initialDirectory="Jobs/PlugIns" logFile="toString.log">
	    <plugin type="rbnb" port="localhost:3333" name="ToString" />
	</toString>
	<thumbNail initialDirectory="Jobs/PlugIns" logFile="thumbNail.log" scale="0.5" quality="0.9" maxImages="10">
	    <plugin type="rbnb" port="localhost:3333" name="ThumbNail" />
	</thumbNail>
	
	<sleep duration_ms="5000"/>
	
	<!-- Data Capture -->
	<del initialDirectory="Capture/DirectIP" file="*.log"/>
	<runProcess tag="DirectIPServer" classification="source" initialDirectory="../INDS-Utility/DirectIPServer/dist" executable="/usr/bin/java" arguments="-cp ./directipserver.jar:../../../RBNB/V3.2B3/bin/rbnb.jar com.erigo.directip.DirectIPServer 1537 localhost:3333" />
	<sleep duration_ms="5000"/>
	
	<!-- Project (demux) -->
	<del initialDirectory="Projects/Beacon" file="*.log"/>
	<csvDemux initialDirectory="Projects/Beacon" logFile="CSVDemux.log" dateFormat="yyyy-MM-dd'T'HH:mm:ss'Z'" silentMode="true" checkEmbeddedTimestamp="true" xmlFile="Beacon.xml">
            <input type="rbnb" port="localhost:3333" channel="SBD/payload"/>
            <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="false" name="Beacon"/>
        </csvDemux>
	
</startup>

=== mcenirm-forks/nasa-dryden-dt/trunk/TwinOtter/TwinOtter_startup.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- TwinOtter project -->

<!--startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd"-->
<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/user/DryScan/nasa-dryden-dt/TwinOtter/inds_startup.xsd">
	
	<!-- Tomcat -->
	<!-- Don't start Tomcat under the Execution Manager -->
	<!--tomcat logFile="tommy.log">
		<input type="tcp" port="localhost:80" />
	</tomcat-->
	
	<!-- Server -->
	<del initialDirectory="Server" file="rbnb.log"/>
	<dataTurbine jvmMaxHeap="1024M" initialDirectory="Server" logFile="rbnb.log" name="INDS" address=":3333" tag="TwinOtter DT"/>
	<sleep duration_ms="15000"/>
	
	<!-- Jobs/KMLTrack -->
	<del initialDirectory="Jobs/KMLTrack" file="*.log"/>
	<trackKML initialDirectory="Jobs/KMLTrack" logFile="TrackKMLTwinOtter.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigTwinOtter.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_TwinOtter" />
	</trackKML>
	<trackData initialDirectory="Jobs/KMLTrack" logFile="TrackDataTwinOtter.log" noGUI="true" configFile="TrackDataConfigTwinOtter.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_TwinOtter" />
	</trackData>
	<sleep duration_ms="2000"/>
	
	<!-- Jobs/TimeDrive -->
	<del initialDirectory="Jobs/TimeDrive" file="*.log"/>
	<timeDrive initialDirectory="Jobs/TimeDrive" logFile="timedrive.log" multiUserMode="ip">
	    <input type="tcp" port="4000"/>
	    <output type="tcp" port="localhost:80"/>
	</timeDrive>
	<sleep duration_ms="2000"/>
	
	<!-- Jobs/PlugIns -->
	<del initialDirectory="Jobs/PlugIns" file="*.log"/>
	<png initialDirectory="Jobs/PlugIns" logFile="png.log" width="320" height="200">
	    <plugin type="rbnb" port="localhost:3333" name="PNGPlugIn" />
	</png>
	<sleep duration_ms="1000"/>
	<toString initialDirectory="Jobs/PlugIns" logFile="toString.log">
	    <plugin type="rbnb" port="localhost:3333" name="ToString" />
	</toString>
	<sleep duration_ms="1000"/>
	<thumbNail initialDirectory="Jobs/PlugIns" logFile="thumbNail.log" scale="0.5" quality="0.9" maxImages="10">
	    <plugin type="rbnb" port="localhost:3333" name="ThumbNail" />
	</thumbNail>
	<sleep duration_ms="5000"/>
	
	<!-- TwinOtter Capture -->
	<del initialDirectory="Projects/TwinOtter" file="*.log"/>
	<!-- FOR LINUX -->
	<!--runProcess tag="TwinOtter-FlightAware" classification="source" initialDirectory="Capture/FlightMonitor" executable="/usr/bin/java" arguments="-cp ../../../INDS-Utility/FlightMonitor/FlightMonitor.jar:../../../INDS-Utility/FlightMonitor/saaj.jar:../../../INDS-Utility/FlightMonitor/activation.jar:../../../INDS-Utility/FlightMonitor/mail.jar com.rbnb.flight.FlightMonitor flightAwareTwinOtter.xml" />
	<runProcess tag="TwinOtter-SkyConnect" classification="source" initialDirectory="Capture/FlightMonitor" executable="/usr/bin/java" arguments="-cp ../../../INDS-Utility/FlightMonitor/FlightMonitor.jar:../../../INDS-Utility/FlightMonitor/saaj.jar:../../../INDS-Utility/FlightMonitor/activation.jar:../../../INDS-Utility/FlightMonitor/mail.jar com.rbnb.flight.FlightMonitor skyConnectTwinOtter.xml" /-->
	<!-- FOR WINDOWS -->
	<runProcess tag="TwinOtter-FlightAware" classification="source" initialDirectory="Capture/FlightMonitor" executable="C:\Program Files\Java\jre6\bin\java.exe" arguments="-cp ../../../INDS-Utility/FlightMonitor/FlightMonitor.jar;../../../INDS-Utility/FlightMonitor/saaj.jar;../../../INDS-Utility/FlightMonitor/activation.jar;../../../INDS-Utility/FlightMonitor/mail.jar com.rbnb.flight.FlightMonitor flightAwareTwinOtter.xml" />
	<runProcess tag="TwinOtter-SkyConnect" classification="source" initialDirectory="Capture/FlightMonitor" executable="C:\Program Files\Java\jre6\bin\java.exe" arguments="-cp ../../../INDS-Utility/FlightMonitor/FlightMonitor.jar;../../../INDS-Utility/FlightMonitor/saaj.jar;../../../INDS-Utility/FlightMonitor/activation.jar;../../../INDS-Utility/FlightMonitor/mail.jar com.rbnb.flight.FlightMonitor skyConnectTwinOtter.xml" />
	
</startup>

=== mcenirm-forks/nasa-dryden-dt/INDSExecutionManager/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- A first cut at describing the P3 INDS system using Bill Finger's INDS Execution Manager schema.                 -->
<!-- Only the RBNB Server is started in a separate directory; all other processes are started in the base directory. -->

<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd">
	
	<!-- Tomcat -->
	<tomcat logFile="tommy.log">
		<input type="tcp" port="localhost:80" />
	</tomcat>
	
	<!-- Server -->
	<del initialDirectory="Server" file="rbnb.log"/>
	<dataTurbine 
			jvmMaxHeap="1024M" 
			initialDirectory="Server" 
			logFile="rbnb.log" name="INDS" address=":3333"/>
	<sleep duration_ms="1500"/>
	
	<!-- Delete all the log files -->
	<del file="*.log"/>
	
	<!-- Jobs/KMLTrack -->
	<trackKML logFile="TrackKMLDC8.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigDC8.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_DC8" />
	</trackKML>
	<trackKML logFile="TrackKMLP3B.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigP3B.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_P3B" />
	</trackKML>
	<trackKML logFile="TrackKMLB200.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigB200.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_B200" />
	</trackKML>
	<trackKML logFile="TrackKMLNOAAP3.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigNOAAP3.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_NOAAP3" />
	</trackKML>
	<trackKML logFile="TrackKMLCV580.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigCV580.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_CV580" />
	</trackKML>
	<trackKML logFile="TrackKMLTwinOtter.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigTwinOtter.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_TwinOtter" />
	</trackKML>
	<trackData logFile="TrackDataDC8.log" noGUI="true" configFile="TrackDataConfigDC8.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_DC8" />
	</trackData>
	<trackData logFile="TrackDataP3B.log" noGUI="true" configFile="TrackDataConfigP3B.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_P3B" />
	</trackData>
	<trackData logFile="TrackDataB200.log" noGUI="true" configFile="TrackDataConfigB200.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_B200" />
	</trackData>
	<trackData logFile="TrackDataNOAAP3.log" noGUI="true" configFile="TrackDataConfigNOAAP3.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_NOAAP3" />
	</trackData>
	<trackData logFile="TrackDataCV580.log" noGUI="true" configFile="TrackDataConfigCV580.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_CV580" />
	</trackData>
	<trackData logFile="TrackDataTwinOtter.log" noGUI="true" configFile="TrackDataConfigTwinOtter.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_TwinOtter" />
	</trackData>
	<sleep duration_ms="200"/>
	
	<!-- Jobs/TimeDrive -->
	<timeDrive logFile="timedrive.log" multiUserMode="ip">
	    <input type="tcp" port="4000"/>
	    <output type="tcp" port="localhost:80"/>
	</timeDrive>
	<sleep duration_ms="200"/>
	
	<!-- Jobs/PlugIns -->
	<png width="320" height="200">
	    <plugin type="rbnb" port="localhost:3333" name="PNGPlugIn" />
	</png>
	<sleep duration_ms="100"/>
	<toString>
	    <plugin type="rbnb" port="localhost:3333" name="ToString" />
	</toString>
	<sleep duration_ms="100"/>
	<thumbNail scale="0.5" quality="0.9" maxImages="10">
	    <plugin type="rbnb" port="localhost:3333" name="ThumbNail" />
	</thumbNail>
	<sleep duration_ms="500"/>
	
	<!-- DC8 project -->
	<xmlDemux logFile="IWG1DemuxDC8.log"  silentMode="true" 
			chanNameFromID="true" xmlFile="IWG1_GTR_OUT_DC8.XML"  >
		<input type="rbnb" port="localhost:3333" channel="DC8-5000-cap/UDP" />
		<output type="rbnb" port="localhost:3333"
				cacheFrames="200" archiveFrames="1000000" 
				overwriteArchive="true" />
	</xmlDemux>
	<sleep duration_ms="100"/>
	
	<!-- P3B project -->
	<xmlDemux logFile="IWG1DemuxP3B.log" silentMode="true" chanNameFromID="true" xmlFile="IWG1_INDS_OUT_P3B.XML">
	    <input type="rbnb" port="localhost:3333" channel="P3B-5700-cap/UDP"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="true"/>
	</xmlDemux>
	<sleep duration_ms="100"/>
	<xmlDemux logFile="HskpngDemuxP3B.log" silentMode="true" chanNameFromID="true" xmlFile="SCAN_GTR_OUT_P3B.XML">
	    <input type="rbnb" port="localhost:3333" channel="P3B-5750-cap/UDP"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="true"/>
	</xmlDemux>
	<sleep duration_ms="200"/>
	
	<!-- B200 project -->
	<csvDemux logFile="CSVDemuxB200.log" dateFormat="yyyyMMdd\'T\'HHmmss" silentMode="true" checkEmbeddedTimestamp="true" xmlFile="B200.xml">
	    <input type="rbnb" port="localhost:3333" channel="B200/B200_ASR_reduced.txt"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="true"/>
	</csvDemux>
	<sleep duration_ms="100"/>
	
	<!-- NOAA P3 project -->
	<csvDemux logFile="CSVDemuxNOAAP3.log" dateFormat="yyyyMMdd\'T\'HHmmss" silentMode="true" checkEmbeddedTimestamp="true" xmlFile="NOAA_P3.xml">
	    <input type="rbnb" port="localhost:3333" channel="NOAA_P3/WP3D.txt"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="true"/>
	</csvDemux>
	<sleep duration_ms="100"/>
	
	<!-- CV580 project -->
	<csvDemux logFile="CSVDemuxCV580.log" dateFormat="yyyyMMdd\'T\'HHmmss" silentMode="true" checkEmbeddedTimestamp="true" xmlFile="CV580.xml">
	    <input type="rbnb" port="localhost:3333" channel="CV580/_CSV"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="true" name="CV580_IWG1"/>
	</csvDemux>
	<sleep duration_ms="100"/>
	
	<!-- Twin Otter project -->
	<csvDemux logFile="TwinOtterDemux.log" dateFormat="yyyy-MM-dd\'T\'HH:mm:ss\'Z\'" silentMode="true" checkEmbeddedTimestamp="true" xmlFile="TwinOtter.xml">
	    <input type="rbnb" port="localhost:3333" channel="P3B-5800-cap/UDP"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="true"/>
	</csvDemux>
	<deadReckoning logFile="DeadReckoning.log" maxLatency_sec="1800"/>
	
	<sleep duration_ms="500"/>
	
	<!-- Capture, HttpMonitor -->
	<httpMonitor logFile="HttpMon_MSFC.log" configFile="HttpMon_MSFC.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_B200.log" configFile="HttpMon_B200.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_DC8.log" configFile="HttpMon_DC8.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_DIAL.log" configFile="HttpMon_DIAL.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_CV580.log" configFile="HttpMon_CV580.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_NOAA_P3.log" configFile="HttpMon_NOAA_P3.xml"/>
	<sleep duration_ms="100"/>
	
	<!-- Capture, UDPcapture -->
	<udpCapture logFile="P3B-5700-cap.log">
	    <input type="udp" port="5700"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="P3B-5700-cap"/>
	</udpCapture>
	<udpCapture logFile="P3B-5750-cap.log">
	    <input type="udp" port="5750"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="P3B-5750-cap"/>
	</udpCapture>
	<udpCapture logFile="P3B-5800-cap.log">
	    <input type="udp" port="5800"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="P3B-5800-cap"/>
	</udpCapture>
	<sleep duration_ms="100"/>

</startup>
