=== mcenirm-forks/nasa-dryden-dt/XML_startup_P3_example/inds_startup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="startup" type="StartupType"/>

<xsd:complexType name="StartupType">
	<xsd:sequence>
		<xsd:element ref="command" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="PortType" >
	<xsd:attribute name="type" type="xsd:string" use="required" />
	<xsd:attribute name="port" type="xsd:string" />
	<!-- type="rbnb" specific attributes, grouped here for simplicity. -->
	<xsd:attribute name="name" type="xsd:string" /> <!-- of Source or Sink -->
	<xsd:attribute name="channel" type="xsd:string" />
	<xsd:attribute name="cacheFrames" type="xsd:nonNegativeInteger"/>
	<xsd:attribute name="archiveFrames" type="xsd:nonNegativeInteger"/>
	<xsd:attribute name="overwriteArchive" type="xsd:boolean" />
</xsd:complexType>

<xsd:complexType name="CommandType" abstract="true">
	<xsd:sequence>
		<xsd:element name="input" type="PortType" 
				minOccurs="0" maxOccurs="unbounded"/>
		<xsd:element name="output" type="PortType" 
				minOccurs="0" maxOccurs="unbounded" />
	</xsd:sequence>
	<xsd:attribute name="initialDirectory" type="xsd:string"/>
	<xsd:attribute name="logFile" type="xsd:string"/>
	<xsd:attribute name="tag" type="xsd:string"/>	
</xsd:complexType>

<xsd:complexType name="JavaCommandType" abstract="true">
	<xsd:complexContent>
		<xsd:extension base="CommandType">
			<xsd:attribute name="jvmMaxHeap" type="xsd:string"/>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="PluginType" abstract="true">
	<xsd:complexContent>
		<xsd:extension base="JavaCommandType">
			<xsd:sequence>
				<xsd:element name="plugin" type="PortType" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:element name="command" type="CommandType" 
		abstract="true" block="restriction" />

<!-- Non-java commands: -->
<xsd:element name="del" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="CommandType">
				<xsd:attribute name="file" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="sleep" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="CommandType">
				<xsd:attribute name="duration_ms" type="xsd:nonNegativeInteger"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<!-- Java applications: -->
<xsd:element name="dataTurbine" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="name" type="xsd:string"/>
				<xsd:attribute name="address" type="xsd:string"/>
				<xsd:attribute name="parent" type="xsd:string"/>
				<xsd:attribute name="loadArchivesAtStart" type="xsd:boolean"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="xmlDemux" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="chanNameFromID" type="xsd:boolean"/>
				<xsd:attribute name="silentMode" type="xsd:boolean"/>
				<xsd:attribute name="xmlFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="csvDemux" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="chanNameFromID" type="xsd:boolean"/>
				<xsd:attribute name="checkEmbeddedTimestamp" type="xsd:boolean"/>
				<xsd:attribute name="dateFormat" type="xsd:string"/>
				<xsd:attribute name="silentMode" type="xsd:boolean"/>
				<xsd:attribute name="xmlFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="udpCapture" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="httpMonitor" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="configFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="tomcat" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="CommandType"/>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="timeDrive" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="JavaCommandType">
				<xsd:attribute name="multiUserMode">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="off"/>
							<xsd:enumeration value="ip"/>
							<xsd:enumeration value="username_password"/>
							<xsd:enumeration value="combination"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>


<!-- DataTurbine Plugins -->
<xsd:element name="png" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="width" type="xsd:integer"/>
				<xsd:attribute name="height" type="xsd:integer"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="toString" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType"/>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="thumbNail" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="scale" type="xsd:double"/>
				<xsd:attribute name="quality" type="xsd:double"/>
				<xsd:attribute name="maxImages" type="xsd:positiveInteger"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="trackData" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="noGUI" type="xsd:boolean"/>
				<xsd:attribute name="configFile" type="xsd:string"/>
				<xsd:attribute name="compression" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="trackKML" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="consolidateResponse" type="xsd:boolean"/>
				<xsd:attribute name="noGUI" type="xsd:boolean"/>
				<xsd:attribute name="configFile" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="deadReckoning" substitutionGroup="command">
	<xsd:complexType>
		<xsd:complexContent>
			<xsd:extension base="PluginType">
				<xsd:attribute name="maxLatency_sec">
					<xsd:simpleType>
						<xsd:restriction base="xsd:double">
							<xsd:minInclusive value="0"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:element>

</xsd:schema>

=== mcenirm-forks/nasa-dryden-dt/trunk/G-III/G-III_startup.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- G-III project -->

<!--startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd"-->
<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/user/DryScan/nasa-dryden-dt/G-III/inds_startup.xsd">
	
	<!-- Tomcat -->
	<!-- Doesn't work with the new Tomcat (apache-tomcat-6.0.18) -->
	<!-- tomcat initialDirectory="Tomcat" logFile="tommy.log">
		<input type="tcp" port="localhost:80" />
	</tomcat>
	<sleep duration_ms="5000"/-->
	
	<!-- Server -->
	<del initialDirectory="Server" file="rbnb.log"/>
	<dataTurbine jvmMaxHeap="1024M" initialDirectory="Server" logFile="rbnb.log" name="INDS" address=":3333" tag="G-III_DT"/>
	<sleep duration_ms="15000"/>
	
	<!-- Jobs/PlugIns -->
	<del initialDirectory="Jobs/PlugIns" file="*.log"/>
	<png initialDirectory="Jobs/PlugIns" logFile="png.log" width="320" height="200">
	    <plugin type="rbnb" port="localhost:3333" name="PNGPlugIn" />
	</png>
	<toString initialDirectory="Jobs/PlugIns" logFile="toString.log">
	    <plugin type="rbnb" port="localhost:3333" name="ToString" />
	</toString>
	<thumbNail initialDirectory="Jobs/PlugIns" logFile="thumbNail.log" scale="0.5" quality="0.9" maxImages="10">
	    <plugin type="rbnb" port="localhost:3333" name="ThumbNail" />
	</thumbNail>
	<sleep duration_ms="3000"/>
	
	<!-- Start rbnbFolder -->
	<del initialDirectory="Capture/rbnbFolder" file="*.log"/>
	<runProcess tag="jplimages" classification="source" initialDirectory="../RBNB/V3.2B3/bin" executable="/usr/bin/java" arguments="-jar folder.jar -a localhost -f /usr/local/JPLimages -m create -D" />
	<sleep duration_ms="15000"/>
	
	<!--                                -->
	<!-- UDPCapture/UDPCaster processes -->
	<!--                                -->
	
	<!-- DCAPS (IWG1 packet) -->
	<del initialDirectory="CaptureCaster/DCAPS" file="*.log"/>
	<udpCapture initialDirectory="CaptureCaster/DCAPS" logFile="DCAPS-capture.log">
	    <input type="udp" port="5800"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="DCAPS-cap"/>
	</udpCapture>
	<runProcess tag="DCAPS-caster" classification="plugin" logFile="DCAPS-caster.log" initialDirectory="../RBNB/V3.2B3/bin" executable="/usr/bin/java" arguments="-jar udpcaster.jar -c DCAPS-cap/UDP -g -i -r 130.134.183.40:5900 -x" />
	
	<!-- UAVSAR out sending to port 5902 -->
	<del initialDirectory="CaptureCaster/UAVSAR-5902" file="*.log"/>
	<udpCapture initialDirectory="CaptureCaster/UAVSAR-5902" logFile="UAVSAR-5902-capture.log">
	    <input type="udp" port="5902"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="UAVSAR-5902-cap"/>
	</udpCapture>
	<runProcess tag="UAVSAR-5903-caster" classification="plugin" logFile="UAVSAR-5903-caster.log" initialDirectory="../RBNB/V3.2B3/bin" executable="/usr/bin/java" arguments="-jar udpcaster.jar -c UAVSAR-5902-cap/UDP -g -i -r 130.134.183.40:5903 -x" />
	
	<!-- UAVSAR out sending to port 5904 -->
	<del initialDirectory="CaptureCaster/UAVSAR-5904" file="*.log"/>
	<udpCapture initialDirectory="CaptureCaster/UAVSAR-5904" logFile="UAVSAR-5904-capture.log">
	    <input type="udp" port="5904"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="UAVSAR-5904-cap"/>
	</udpCapture>
	<runProcess tag="UAVSAR-5905-caster" classification="plugin" logFile="UAVSAR-5905-caster.log" initialDirectory="../RBNB/V3.2B3/bin" executable="/usr/bin/java" arguments="-jar udpcaster.jar -c UAVSAR-5904-cap/UDP -g -i -r 130.134.183.40:5905 -x" />
	
	<!-- UAVSAR comm link -->
	<del initialDirectory="CaptureCaster/UAVSAR-5907" file="*.log"/>
	<udpCapture initialDirectory="CaptureCaster/UAVSAR-5907" logFile="UAVSAR-5907-capture.log">
	    <input type="udp" port="5907"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="UAVSAR-5907-cap"/>
	</udpCapture>
	<runProcess tag="UAVSAR-5906-caster" classification="plugin" logFile="UAVSAR-5906-caster.log" initialDirectory="../RBNB/V3.2B3/bin" executable="/usr/bin/java" arguments="-jar udpcaster.jar -c UAVSAR-5907-cap/UDP -g -i -r 192.168.8.100:5906 -x" />
	
	<!-- UAVSAR input command line -->
	<del initialDirectory="CaptureCaster/UAVSAR-5909" file="*.log"/>
	<udpCapture initialDirectory="CaptureCaster/UAVSAR-5909" logFile="UAVSAR-5909-capture.log">
	    <input type="udp" port="5909"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="true" name="UAVSAR-5909-cap"/>
	</udpCapture>
	<runProcess tag="UAVSAR-5908-caster" classification="plugin" logFile="UAVSAR-5908-caster.log" initialDirectory="../RBNB/V3.2B3/bin" executable="/usr/bin/java" arguments="-jar udpcaster.jar -c UAVSAR-5909-cap/UDP -g -i -r 192.168.8.100:5908 -x" />
	
	<sleep duration_ms="15000"/>
	
	<!-- Start MakeTimeMirror -->
	<del initialDirectory="Jobs/MakeTimeMirror" file="*.log"/>
	<runProcess tag="TimeMirror" classification="source" initialDirectory="../INDS-Utility/MakeTimeMirror" executable="/usr/bin/java" arguments="-cp /usr/local/software/INDSExecutionManager/trunk/INDS-Utility/MakeTimeMirror:/usr/local/software/INDSExecutionManager/trunk/RBNB/V3.2B3/bin/rbnb.jar MakeTimeMirror localhost:3333 Folder 130.134.86.73:3333 jplimages" />
	
</startup>

=== mcenirm-forks/nasa-dryden-dt/trunk/INDSExecutionManager/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- A first cut at describing the P3 INDS system using Bill Finger's INDS Execution Manager schema.                 -->
<!-- Only the RBNB Server is started in a separate directory; all other processes are started in the base directory. -->

<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd">
	
	<!-- Tomcat -->
	<tomcat logFile="tommy.log" />
	
	<!-- Server -->
	<del initialDirectory="Server" file="rbnb.log"/>
	<dataTurbine jvmMaxHeap="1024M" initialDirectory="Server" logFile="rbnb.log" name="INDS" address=":3333"/>
	<sleep duration_ms="1500"/>
	
	<!-- Delete all the log files -->
	<del file="*.log"/>
	
	<!-- Jobs/KMLTrack -->
	<trackKML logFile="TrackKMLDC8.log" name="TrackKML_DC8" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigDC8.txt"/>
	<trackKML logFile="TrackKMLP3B.log" name="TrackKML_P3B" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigP3B.txt"/>
	<trackKML logFile="TrackKMLB200.log" name="TrackKML_B200" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigB200.txt"/>
	<trackKML logFile="TrackKMLNOAAP3.log" name="TrackKML_NOAAP3" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigNOAAP3.txt"/>
	<trackKML logFile="TrackKMLCV580.log" name="TrackKML_CV580" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigCV580.txt"/>
	<trackKML logFile="TrackKMLTwinOtter.log" name="TrackKML_TwinOtter" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigTwinOtter.txt"/>
	<trackData logFile="TrackDataDC8.log" name="TrackData_DC8" noGUI="true" configFile="TrackDataConfigDC8.txt"/>
	<trackData logFile="TrackDataP3B.log" name="TrackData_P3B" noGUI="true" configFile="TrackDataConfigP3B.txt"/>
	<trackData logFile="TrackDataB200.log" name="TrackData_B200" noGUI="true" configFile="TrackDataConfigB200.txt"/>
	<trackData logFile="TrackDataNOAAP3.log" name="TrackData_NOAAP3" noGUI="true" configFile="TrackDataConfigNOAAP3.txt"/>
	<trackData logFile="TrackDataCV580.log" name="TrackData_CV580" noGUI="true" configFile="TrackDataConfigCV580.txt"/>
	<trackData logFile="TrackDataTwinOtter.log" name="TrackData_TwinOtter" noGUI="true" configFile="TrackDataConfigTwinOtter.txt"/>
	<sleep duration_ms="200"/>
	
	<!-- Jobs/TimeDrive -->
	<timeDrive logFile="timedrive.log" listenPort="4000" webserverAddress="localhost" multiUserMode="2"/>
	<sleep duration_ms="200"/>
	
	<!-- Jobs/PlugIns -->
	<png name="PNGPlugIn" hostAddress="localhost:3333" width="320" height="200"  />
	<sleep duration_ms="100"/>
	<toString name="ToString"/>
	<sleep duration_ms="100"/>
	<thumbNail name="ThumbNail" scale="0.5" quality="0.9" maxImages="10"/>
	<sleep duration_ms="500"/>
	
	<!-- DC8 project -->
	<xmlDemux logFile="IWG1DemuxDC8.log" inputDT="localhost:3333" outputDT="localhost:3333" silentMode="true" chanNameFromID="true" inputName="DC8-5000-cap/UDP" xmlFile="IWG1_GTR_OUT_DC8.XML" cacheFrames="200" archiveFrames="1000000" createNewArchive="true"/>
	<sleep duration_ms="100"/>
	
	<!-- P3B project -->
	<xmlDemux logFile="IWG1DemuxP3B.log" inputDT="localhost:3333" outputDT="localhost:3333" silentMode="true" chanNameFromID="true" inputName="P3B-5700-cap/UDP" xmlFile="IWG1_INDS_OUT_P3B.XML" cacheFrames="200" archiveFrames="1000000" createNewArchive="true"/>
	<sleep duration_ms="100"/>
	<xmlDemux logFile="HskpngDemuxP3B.log" inputDT="localhost:3333" outputDT="localhost:3333" silentMode="true" chanNameFromID="true" inputName="P3B-5750-cap/UDP" xmlFile="SCAN_GTR_OUT_P3B.XML" cacheFrames="200" archiveFrames="1000000" createNewArchive="true"/>
	<sleep duration_ms="200"/>
	
	<!-- B200 project -->
	<csvDemux logFile="CSVDemuxB200.log" inputDT="localhost:3333" outputDT="localhost:3333" dateFormat="yyyyMMdd\'T\'HHmmss" silentMode="true" checkEmbeddedTimestamp="true" inputName="B200/B200_ASR_reduced.txt" xmlFile="B200.xml" cacheFrames="200" archiveFrames="1000000" createNewArchive="true"/>
	<sleep duration_ms="100"/>
	
	<!-- NOAA P3 project -->
	<csvDemux logFile="CSVDemuxNOAAP3.log" inputDT="localhost:3333" outputDT="localhost:3333" dateFormat="yyyyMMdd\'T\'HHmmss" silentMode="true" checkEmbeddedTimestamp="true" inputName="NOAA_P3/WP3D.txt" xmlFile="NOAA_P3.xml" cacheFrames="200" archiveFrames="1000000" createNewArchive="true"/>
	<sleep duration_ms="100"/>
	
	<!-- CV580 project -->
	<csvDemux logFile="CSVDemuxCV580.log" inputDT="localhost:3333" outputDT="localhost:3333" dateFormat="yyyyMMdd\'T\'HHmmss" silentMode="true" checkEmbeddedTimestamp="true" inputName="CV580/_CSV" xmlFile="CV580.xml" cacheFrames="200" archiveFrames="1000000" createNewArchive="true" outputSource="CV580_IWG1"/>
	<sleep duration_ms="100"/>
	
	<!-- Twin Otter project -->
	<csvDemux logFile="TwinOtterDemux.log" inputDT="localhost:3333" outputDT="localhost:3333" dateFormat="yyyy-MM-dd\'T\'HH:mm:ss\'Z\'" silentMode="true" checkEmbeddedTimestamp="true" inputName="P3B-5800-cap/UDP" xmlFile="TwinOtter.xml" cacheFrames="200" archiveFrames="1000000" createNewArchive="true"/>
	<deadReckoning logFile="DeadReckoning.log" maxLatency_sec="1800"/>
	
	<sleep duration_ms="500"/>
	
	<!-- Capture, HttpMonitor -->
	<httpMonitor logFile="HttpMon_MSFC.log" configFile="HttpMon_MSFC.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_B200.log" configFile="HttpMon_B200.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_DC8.log" configFile="HttpMon_DC8.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_DIAL.log" configFile="HttpMon_DIAL.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_CV580.log" configFile="HttpMon_CV580.xml"/>
	<sleep duration_ms="100"/>
	<httpMonitor logFile="HttpMon_NOAA_P3.log" configFile="HttpMon_NOAA_P3.xml"/>
	<sleep duration_ms="100"/>
	
	<!-- Capture, UDPcapture -->
	<udpCapture logFile="P3B-5700-cap.log" listenPort="5700" cacheFrames="10" archiveFrames="8640000" createNewArchive="true" name="P3B-5700-cap"/>
	<udpCapture logFile="P3B-5750-cap.log" listenPort="5750" cacheFrames="10" archiveFrames="8640000" createNewArchive="true" name="P3B-5750-cap"/>
	<udpCapture logFile="P3B-5800-cap.log" listenPort="5800" cacheFrames="10" archiveFrames="8640000" createNewArchive="true" name="P3B-5800-cap"/>
	<sleep duration_ms="100"/>

</startup>

=== mcenirm-forks/nasa-dryden-dt/trunk/UWyoKingAir/UWyoKingAir_startup.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- University of Wyoming King Air project -->

<!--startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://whf/schema/inds_startup.xsd"-->
<startup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/user/DryScan/nasa-dryden-dt/UWyoKingAir/inds_startup.xsd">
	
	<!-- Tomcat -->
	<!-- Doesn't work with the new Tomcat (apache-tomcat-6.0.18) -->
	<!-- tomcat initialDirectory="Tomcat" logFile="tommy.log">
		<input type="tcp" port="localhost:80" />
	</tomcat>
	<sleep duration_ms="5000"/-->
	
	<!-- Server -->
	<del initialDirectory="Server" file="rbnb.log"/>
	<dataTurbine jvmMaxHeap="1024M" initialDirectory="Server" logFile="rbnb.log" name="INDS" address=":3333" tag="UWyoKingAir DT"/>
	<sleep duration_ms="15000"/>
	
	<!-- Jobs/KMLTrack -->
	<del initialDirectory="Jobs/KMLTrack" file="*.log"/>
	<trackKML initialDirectory="Jobs/KMLTrack" logFile="TrackKMLUWyoKingAir.log" consolidateResponse="true" noGUI="true" configFile="TrackKMLConfigUWyoKingAir.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackKML_UWyoKingAir" />
	</trackKML>
	<trackData initialDirectory="Jobs/KMLTrack" logFile="TrackDataUWyoKingAir.log" noGUI="true" configFile="TrackDataConfigUWyoKingAir.txt">
	    <plugin type="rbnb" port="localhost:3333" name="TrackData_UWyoKingAir" />
	</trackData>
	
	<!-- Jobs/TimeDrive -->
	<del initialDirectory="Jobs/TimeDrive" file="*.log"/>
	<timeDrive initialDirectory="Jobs/TimeDrive" logFile="timedrive.log" multiUserMode="ip">
	    <input type="tcp" port="4000"/>
	    <output type="tcp" port="localhost:80"/>
	</timeDrive>
	
	<!-- Jobs/PlugIns -->
	<del initialDirectory="Jobs/PlugIns" file="*.log"/>
	<png initialDirectory="Jobs/PlugIns" logFile="png.log" width="320" height="200">
	    <plugin type="rbnb" port="localhost:3333" name="PNGPlugIn" />
	</png>
	<toString initialDirectory="Jobs/PlugIns" logFile="toString.log">
	    <plugin type="rbnb" port="localhost:3333" name="ToString" />
	</toString>
	<thumbNail initialDirectory="Jobs/PlugIns" logFile="thumbNail.log" scale="0.5" quality="0.9" maxImages="10">
	    <plugin type="rbnb" port="localhost:3333" name="ThumbNail" />
	</thumbNail>
	
	<sleep duration_ms="5000"/>
	
	<!-- Data Capture -->
	<del initialDirectory="Capture/UDPCapture" file="*.log"/>
	<udpCapture initialDirectory="Capture/UDPCapture" logFile="UWyoKingAir-50000-cap.log">
	    <input type="udp" port="50000"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="10" archiveFrames="8640000" overwriteArchive="false" name="UWyoKingAir-50000-cap"/>
	</udpCapture>
	<sleep duration_ms="5000"/>
	
	<!-- Project (demux) -->
	<del initialDirectory="Projects/UWyoKingAir" file="*.log"/>
	<xmlDemux initialDirectory="Projects/UWyoKingAir" logFile="XMLDemux.log" silentMode="true" chanNameFromID="true" xmlFile="demux.xml">
	    <input type="rbnb" port="localhost:3333" channel="UWyoKingAir-50000-cap/UDP"/>
	    <output type="rbnb" port="localhost:3333" cacheFrames="200" archiveFrames="1000000" overwriteArchive="false" name="UWYO_KING_AIR"/>
	</xmlDemux>
	
</startup>
